pipeline {
    agent any

    environment {
        // Nexus credentials from Jenkins (UsernamePassword type)
        NEXUS_CREDENTIALS = credentials('jenkins-user')  
    }

    stages {
        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('biro-sample') {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                sh """
                  mvn deploy \
                    -Dnexus.username=$NEXUS_CREDENTIALS_USR \
                    -Dnexus.password=$NEXUS_CREDENTIALS_PSW
                """
            }
        }
    }
}
