pipeline {
    agent any
    tools {
        maven 'Maven-3.9.11'  // Must exactly match the Name in Jenkins tool config
    }

    environment {
        NEXUS_CREDENTIALS = credentials('biro-nexus')
        SONAR_TOKEN = credentials('biro-sonar-token') // SonarQube authentication token
    }

    stages {
        stage('Check Maven') {
            steps {
                sh 'mvn -v'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('biro-sample') {
                    sh """
                       mvn sonar:sonar \
                         -Dsonar.projectKey=com.yourcompany.biro-sample \
                         -Dsonar.projectName=biro-Sample \
                         -Dsonar.login=$SONAR_TOKEN
                    """
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                sh """
                  mvn deploy \
                    -Dnexus.username=$NEXUS_CREDENTIALS_USR \
                    -Dnexus.password=$NEXUS_CREDENTIALS_PSW
                """
            }
        }
    }
}
